Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [144 B]
Hit:6 https://packages.microsoft.com/repos/azure-cli noble InRelease
Get:7 https://packages.microsoft.com/ubuntu/24.04/prod noble InRelease [3600 B]
Get:8 https://dl.google.com/linux/chrome-stable/deb stable InRelease [1825 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu noble InRelease
Get:3 http://azure.archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
Get:5 http://azure.archive.ubuntu.com/ubuntu noble-security InRelease [126 kB]
Get:9 https://packages.microsoft.com/ubuntu/24.04/prod noble/main arm64 Packages [156 kB]
Get:10 https://packages.lunarg.com/vulkan jammy InRelease
Get:11 https://packages.microsoft.com/ubuntu/24.04/prod noble/main amd64 Packages [187 kB]
Get:12 https://dl.google.com/linux/chrome-stable/deb stable/main amd64 Packages [1211 B]
Get:13 http://azure.archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [1041 kB]
Get:14 http://azure.archive.ubuntu.com/ubuntu noble-updates/main Translation-en [261 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu noble-updates/main amd64 Components [181 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu noble-updates/main amd64 c-n-f Metadata [17.5 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [1656 kB]
Get:18 http://azure.archive.ubuntu.com/ubuntu noble-updates/universe Translation-en [326 kB]
Get:19 http://azure.archive.ubuntu.com/ubuntu noble-updates/universe amd64 Components [388 kB]
Get:20 http://azure.archive.ubuntu.com/ubuntu noble-updates/universe amd64 c-n-f Metadata [34.8 kB]
Get:21 http://azure.archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Packages [1134 kB]
Get:22 http://azure.archive.ubuntu.com/ubuntu noble-updates/restricted Translation-en [257 kB]
Get:23 http://azure.archive.ubuntu.com/ubuntu noble-updates/multiverse amd64 Components [940 B]
Get:24 http://azure.archive.ubuntu.com/ubuntu noble-backports/main amd64 Components [5760 B]
Get:25 http://azure.archive.ubuntu.com/ubuntu noble-backports/universe amd64 Components [10.5 kB]
Get:26 http://azure.archive.ubuntu.com/ubuntu noble-security/main amd64 Packages [788 kB]
Get:27 http://azure.archive.ubuntu.com/ubuntu noble-security/main Translation-en [179 kB]
Get:28 http://azure.archive.ubuntu.com/ubuntu noble-security/main amd64 Components [44.9 kB]
Get:29 http://azure.archive.ubuntu.com/ubuntu noble-security/main amd64 c-n-f Metadata [11.6 kB]
Get:30 http://azure.archive.ubuntu.com/ubuntu noble-security/universe amd64 Packages [1171 kB]
Get:31 http://azure.archive.ubuntu.com/ubuntu noble-security/universe Translation-en [229 kB]
Get:32 http://azure.archive.ubuntu.com/ubuntu noble-security/universe amd64 Components [76.3 kB]
Get:33 http://azure.archive.ubuntu.com/ubuntu noble-security/universe amd64 c-n-f Metadata [24.1 kB]
Get:34 http://azure.archive.ubuntu.com/ubuntu noble-security/restricted amd64 Packages [1071 kB]
Get:35 http://azure.archive.ubuntu.com/ubuntu noble-security/restricted Translation-en [245 kB]
Get:36 https://packages.lunarg.com/vulkan jammy/main Sources [198 kB]
Get:37 https://packages.lunarg.com/vulkan jammy/main amd64 Packages [192 kB]
Fetched 10.3 MB in 1s (7671 kB/s)
Reading package lists...
W: https://packages.lunarg.com/vulkan/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 crashdiagnosticlayer : Depends: libyaml-cpp0.7 (>= 0.7.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
